### ISSUE TITLE
Multiple notices, strict warnings

### ISSUE THREAD

**Issue by edvordo** [easyise/eiseXLSX#1]
Great code as it is, outputs Notices about undefined variables $path ( line 49 ) and $t ( line 670 ), which I fixed by commenting out the first one, since it's not used anywhere else in the code anyway and the second one I replaced with static letter " s ".
The strict warnings are related to & on lines 134, 136, 160, 670 and 671. In this case I am not really sure if it's okay to just remove the ampersands ( which fixes the problem ).

One more thing tho', tmp folder does not always have to be writable, it would be nice if the code checked for this first :)

Anyway, as I sad, great library, just minor bugs :)

**Comment by easyise** [comment]
Thanks for the feedback and sorry for latence. 'Notices' are fixed, and '&' signs are not. 
Now I've got project with some big deexcelization work so I plan some improvements in the library. Keep on following, news are coming soon.
