### ISSUE TITLE
Depreciated features with PHP 7.1

### ISSUE THREAD

**Issue by lcwakeman** [easyise/eiseXLSX#13]
Getting:

Deprecated: Non-static method eiseXLSX::letter2index() should not be called statically in C:\Users\larry\Projects\larrywakeman\www\wp-content\plugins\dmc-user-list\objects\eiseXLSX.php on line 1331

Notice: Only variables should be assigned by reference in C:\Users\larry\Projects\larrywakeman\www\wp-content\plugins\dmc-user-list\objects\eiseXLSX.php on line 1155

Notice: Only variables should be assigned by reference in C:\Users\larry\Projects\larrywakeman\www\wp-content\plugins\dmc-user-list\objects\eiseXLSX.php on line 205

Notice: Only variables should be assigned by reference in C:\Users\larry\Projects\larrywakeman\www\wp-content\plugins\dmc-user-list\objects\eiseXLSX.php on line 229

**Comment by easyise** [comment]
Fixed in 1.6.0.2
