### ISSUE TITLE
Data to Named Cells

### ISSUE THREAD

**Issue by BrandnerChris** [easyise/eiseXLSX#4]
Could you add a function to add data to a specific field which is a "named cell" in an Excel-Template.

Something like

> $excel = new eiseXLSX($filename);
> $excel->selectSheet($excel->findSheetByName("MySheet"));
> $excel->data($excel->getNamedCell("NamedCellKey"), "Insert Value");
> ...

**Comment by easyise** [comment]
Sorry for late reply, I just found out what you're asking for :). Named cells can be accesses via its addresses as normal cells. I don't want to make this lib redundant so sorry, the answer is NO.
