### ISSUE TITLE
Writing Dates does not work

### ISSUE THREAD

**Issue by NochEinKamel** [easyise/eiseXLSX#6]
Hi,

thanks for the so far good working library :-)

However there is a small flaw, when tryring to write dates into an excel file.
The function pickupDateStyle used here https://github.com/easyise/eiseXLSX/blob/master/eiseXLSX.php#L875 does not exist :-(

**Comment by easyise** [comment]
Hi Kai, thanks for the feedback,
I suggest you to checkout 'dev' branch, this problem is fixed in there. I going to merge these changes with 'master' as soon as possble, but I have to update some lib docs in it. Stay tuned.
